spring.application.name=gestoreta
spring.datasource.url=jdbc:postgresql://37.135.29.68:2004/postgres?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc.api-docs.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
